name: Run compile check

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build with make
      run: |
        make
      continue-on-error: true

    - name: Check build status
      run: |
        if [ $? -eq 0 ]; then
          echo "Build succeeded!"
        else
          echo "Build failed!"
          exit 1
        fi