name: Run clang-format Linter

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    style: Google

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.16.2
      with:
        source: './src'
        exclude: './lib'
        extensions: 'hpp,cpp'
        clangFormatVersion: 16
