name: Run curl check

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build with make
      run: |
        make

    - name: Run our webserver
      run: |
        ./webserv&

    - name: Build with make
      run: |
        curl localhost:1234

    - name: Build with make
      run: |
        curl localhost:1234/index.html

    - name: Build with make
      run: |
        curl localhost:1234/large.jpg

    - name: Build with make
      run: |
        curl "localhost:1234/sp ace.html"
